=== DavidPutnam/FileProcessor/filespecification.dtd
<!ELEMENT File (Record*)>
<!ATTLIST File
          type (fixed|deliminated) #REQUIRED
          idBegin CDATA #IMPLIED
          idLength CDATA #IMPLIED
          idField CDATA #IMPLIED
          deliminator CDATA #IMPLIED>
<!ELEMENT Record (Attribute*)>
<!ATTLIST Record
          id CDATA #REQUIRED
          firstOfSet (true|false) #IMPLIED
          required (true|false) #IMPLIED
          targetClassName CDATA #IMPLIED
          sameAs CDATA #IMPLIED>
<!ELEMENT Attribute EMPTY>
<!ATTLIST Attribute
          name CDATA #REQUIRED
          format CDATA #IMPLIED
          begin CDATA #IMPLIED
          length CDATA #IMPLIED
          sublength CDATA #IMPLIED
          field CDATA #IMPLIED
          subdelim CDATA #IMPLIED>

=== DavidPutnam/FileProcessor/dtcc_sdr.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE File SYSTEM "filespecification.dtd">
<File type="fixed" idBegin="2" idLength="4">
    <!-- The id includes both the recordType and sequenceNumber but not the originatorType for each record -->
    <Record id="2001" firstOfSet="true" required="true" targetClassName="org.putnamfamily.fileprocessor.dtcc_sdr.Request">
        <Attribute begin="1" length="1" name="originatorType"/>
        <Attribute begin="2" length="2" name="recordType"/>
        <Attribute begin="4" length="2" name="sequenceNumber"/>
        <Attribute begin="6" length="15" name="sdrControlNumber"/>
        <Attribute begin="21" length="4" name="firmNumber"/>
        <Attribute begin="25" length="4" name="fundNumber"/>
        <Attribute begin="29" length="9" name="securityIssueId"/>
        <Attribute begin="38" length="4" name="underlyingFirmNumber"/>
        <Attribute begin="42" length="2" name="underlyingFirmIndicator"/>
        <Attribute begin="44" length="20" name="fundAccountNumber"/>
        <Attribute begin="64" length="20" name="firmAccountNumber"/>
        <Attribute begin="84" length="15" name="fundServControlNumber"/>
        <Attribute begin="99" length="2" name="sdrRequestType"/>
        <Attribute begin="101" length="8" name="fromDate" format="MMddyyyy"/>
        <Attribute begin="109" length="9" name="tin"/>
        <Attribute begin="118" length="24" name="filler1"/>
        <Attribute begin="142" length="1" name="nsccRejectIndicator"/>
        <Attribute begin="143" length="2" name="nsccRejectCode1"/>
        <Attribute begin="145" length="2" name="nsccRejectCode2"/>
        <Attribute begin="147" length="2" name="nsccRejectCode3"/>
        <Attribute begin="149" length="2" name="nsccRejectCode4"/>
    </Record>
    <Record id="2002" firstOfSet="false" required="true" targetClassName="org.putnamfamily.fileprocessor.dtcc_sdr.Request">
        <Attribute begin="1" length="1" name="originatorType"/>
        <Attribute begin="2" length="2" name="recordType"/>
        <Attribute begin="4" length="2" name="sequenceNumber"/>
        <Attribute begin="6" length="20" name="omnibusAccountNumber"/>
        <Attribute begin="26" length="1" name="omnibusAccountIndicator"/>
        <Attribute begin="27" length="1" name="recuringIndicator"/>
        <Attribute begin="28" length="8" name="toDate" format="MMddyyyy"/>
        <Attribute begin="36" length="1" name="category2Indicator"/>
        <Attribute begin="37" length="9" name="rrRep"/>
        <Attribute begin="46" length="9" name="rrBranch"/>
        <Attribute begin="55" length="8" name="rrFirm"/>
        <Attribute begin="63" length="15" name="originalSdrControlNumber"/>
        <Attribute begin="78" length="9" name="thresholdAmount"/>
        <Attribute begin="87" length="2" name="transactionType"/>
        <Attribute begin="89" length="62" name="filler2"/>
    </Record>
    <Record id="2101" firstOfSet="true" required="true" targetClassName="org.putnamfamily.fileprocessor.dtcc_sdr.Header">
        <Attribute begin="1" length="1" name="originatorType"/>
        <Attribute begin="2" length="2" name="recordType"/>
        <Attribute begin="4" length="2" name="sequenceNumber"/>
        <Attribute begin="6" length="15" name="sdrControlNumber"/>
        <Attribute begin="21" length="4" name="firmNumber"/>
        <Attribute begin="25" length="4" name="fundNumber"/>
        <Attribute begin="29" length="9" name="securityIssueId"/>
        <Attribute begin="38" length="4" name="underlyingFirmNumber"/>
        <Attribute begin="42" length="2" name="underlyingFirmIndicator"/>
        <Attribute begin="44" length="20" name="fundAccountNumber"/>
        <Attribute begin="64" length="20" name="firmAccountNumber"/>
        <Attribute begin="84" length="15" name="fundServControlNumber"/>
        <Attribute begin="99" length="2" name="responseType"/>
        <Attribute begin="101" length="15" name="sdrResponseNumber"/>
        <Attribute begin="116" length="1" name="partialResponseIndicator"/>
        <Attribute begin="117" length="1" name="correctionIndicator"/>
        <Attribute begin="118" length="24" name="filler1"/>
        <Attribute begin="142" length="1" name="nsccRejectIndicator"/>
        <Attribute begin="143" length="2" name="nsccRejectCode1"/>
        <Attribute begin="145" length="2" name="nsccRejectCode2"/>
        <Attribute begin="147" length="2" name="nsccRejectCode3"/>
        <Attribute begin="149" length="2" name="nsccRejectCode4"/>
    </Record>
</File>

=== DavidPutnam/FileProcessor/dst_tip.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE File SYSTEM "filespecification.dtd">
<File type="fixed" idBegin="1" idLength="6">
    <!-- The id includes both the recordType and sequenceNumber for each record -->
    <Record id="RHR001" firstOfSet="true" required="true" targetClassName="org.putnamfamily.fileprocessor.dst_tip.Header">
        <Attribute begin="1" length="3" name="recordType"/>
        <Attribute begin="4" length="3" name="sequenceNumber"/>
        <Attribute begin="7" length="15" name="fileType"/>
        <Attribute begin="22" length="8" name="superSheetDate" format="yyyyMMdd"/>
        <Attribute begin="30" length="16" name="processedDate" format="yyyyMMddHHmmssdd"/>
        <Attribute begin="46" length="8" name="jobName"/>
        <Attribute begin="54" length="3" name="fileFormatCode"/>
        <Attribute begin="57" length="7" name="requestNumber"/>
        <Attribute begin="64" length="97" name="unused1"/>
    </Record>
    <Record id="RTR001" firstOfSet="true" required="true" targetClassName="org.putnamfamily.fileprocessor.dst_tip.Trailer">
        <Attribute begin="1" length="3" name="recordType"/>
        <Attribute begin="4" length="3" name="sequenceNumber"/>
        <Attribute begin="7" length="15" name="fileType"/>
        <Attribute begin="22" length="9" name="recordCount"/>
        <Attribute begin="31" length="130" name="unused1"/>
    </Record>
    <Record id="AMP001" firstOfSet="true" required="true" targetClassName="org.putnamfamily.fileprocessor.dst_tip.Account">
        <Attribute begin="1" length="3" name="recordType"/>
        <Attribute begin="4" length="3" name="sequenceNumber"/>
    </Record>
    <Record id="NFA001" sameAs="AMP001"/>
    <Record id="NAA001" sameAs="AMP001"/>
    <Record id="AMP002" firstOfSet="false" required="false" targetClassName="org.putnamfamily.fileprocessor.dst_tip.Account">
        <Attribute begin="1" length="3" name="recordType"/>
        <Attribute begin="4" length="3" name="sequenceNumber"/>
    </Record>
    <Record id="NFA002" sameAs="AMP002"/>
    <Record id="NAA002" sameAs="AMP002"/>
    <Record id="PRI001" firstOfSet="true" required="true" targetClassName="org.putnamfamily.fileprocessor.dst_tip.Price">
        <Attribute begin="1" length="3" name="recordType"/>
        <Attribute begin="4" length="3" name="sequenceNumber"/>
   	</Record>
    <Record id="TRN001" firstOfSet="true" required="true" targetClassName="org.putnamfamily.fileprocessor.dst_tip.Transaction">
        <Attribute begin="1" length="3" name="recordType"/>
        <Attribute begin="4" length="3" name="sequenceNumber"/>
   	</Record>
    <Record id="TRN002" firstOfSet="false" required="false" targetClassName="org.putnamfamily.fileprocessor.dst_tip.Transaction">
        <Attribute begin="1" length="3" name="recordType"/>
        <Attribute begin="4" length="3" name="sequenceNumber"/>
    </Record>
</File>

=== DavidPutnam/FileProcessor/nwd22c2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE File SYSTEM "filespecification.dtd">
<File type="fixed" idBegin="1" idLength="10">
    <Record id="0000000000" firstOfSet="true" required="true" targetClassName="org.putnamfamily.fileprocessor.nwd22c2.Header">
        <Attribute begin="1" length="10" name="recordType"/>
        <Attribute begin="11" length="8" name="cycleDate" format="yyyyMMdd"/>
        <Attribute begin="19" length="8" name="createDate" format="yyyyMMdd"/>
        <Attribute begin="27" length="7" name="company"/>
        <Attribute begin="34" length="667" name="filler"/>
    </Record>
    <Record id="9999999999" firstOfSet="true" required="true" targetClassName="org.putnamfamily.fileprocessor.nwd22c2.Trailer">
        <Attribute begin="1" length="10" name="recordType"/>
        <Attribute begin="11" length="10" name="recordCount"/>
        <Attribute begin="21" length="16" name="amountTotal" format="2"/>
        <Attribute begin="37" length="664" name="filler"/>
    </Record>
    <Record id="?" firstOfSet="true" required="true" targetClassName="org.putnamfamily.fileprocessor.nwd22c2.Price">
        <Attribute begin="1" length="10" name="recordType"/>
        <Attribute begin="4" length="15" name="fundCusipNumber"/>
        <Attribute begin="19" length="5" name="paFundNbr"/>
        <Attribute begin="24" length="8" name="tradeDate" format="yyyyMMdd"/>
        <Attribute begin="32" length="17" name="price"/>
        <Attribute begin="49" length="3" name="cycle"/>
        <Attribute begin="52" length="13" name="factor"/>
        <Attribute begin="65" length="1" name="days"/>
    </Record>
    <Record id="?" firstOfSet="true" required="true" targetClassName="org.putnamfamily.fileprocessor.nwd22c2.Transaction">
        <Attribute begin="1" length="3" name="recordType"/>
        <Attribute begin="4" length="15" name="fundCusipNumber"/>
        <Attribute begin="19" length="5" name="paFundNbr"/>
        <Attribute begin="24" length="8" name="tradeDate" format="yyyyMMdd"/>
        <Attribute begin="32" length="17" name="price"/>
        <Attribute begin="49" length="3" name="cycle"/>
        <Attribute begin="52" length="13" name="factor"/>
        <Attribute begin="65" length="1" name="days"/>
    </Record>
</File>

=== DavidPutnam/FileProcessor/poweragent.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE File SYSTEM "filespecification.dtd">
<File type="fixed" idBegin="1" idLength="1">
    <!-- The id includes both the recordType and sequenceNumber for each record -->
    <Record id="0" firstOfSet="true" targetClassName="org.putnamfamily.fileprocessor.poweragent.Header">
        <Attribute begin="1" length="1" name="recordType"/>
        <Attribute begin="2" length="17" name="createDateTime" format="yyyyMMdd HH:mm:ss"/>
        <Attribute begin="19" length="50" name="fundGroupName"/>
        <Attribute begin="69" length="10" name="version"/>
    </Record>
    <Record id="9" firstOfSet="true" targetClassName="org.putnamfamily.fileprocessor.poweragent.Trailer">
        <Attribute begin="1" length="1" name="recordType"/>
        <Attribute begin="2" length="17" name="endDateTime" format="yyyyMMdd HH:mm:ss"/>
        <Attribute begin="19" length="16" name="recordCount"/>
    </Record>
    <Record id="PRI" firstOfSet="true" targetClassName="org.putnamfamily.fileprocessor.poweragent.Price">
        <Attribute begin="1" length="3" name="recordType"/>
        <Attribute begin="4" length="15" name="fundCusipNumber"/>
        <Attribute begin="19" length="5" name="paFundNbr"/>
        <Attribute begin="24" length="8" name="tradeDate" format="yyyyMMdd"/>
        <Attribute begin="32" length="17" name="price"/>
        <Attribute begin="49" length="3" name="cycle"/>
        <Attribute begin="52" length="13" name="factor"/>
        <Attribute begin="65" length="1" name="days"/>
    </Record>
</File>
